import type { EmployeeSummary, SessionUser } from "@zenops/contracts";
import { type FormEvent, useEffect, useState } from "react";
const roleOptions = [{ code: "WORKER", name: "Pracovník" }, { code: "LEADER", name: "Vedoucí" }, { code: "ADMIN", name: "Admin" }] as const;
export function EmployeePanel({ user }: { user: SessionUser }) {
  const [employees, setEmployees] = useState<EmployeeSummary[]>([]); const [showCreate, setShowCreate] = useState(false); const [editTarget, setEditTarget] = useState<EmployeeSummary | null>(null); const [stateTarget, setStateTarget] = useState<EmployeeSummary | null>(null); const [error, setError] = useState("");
  const load = () => fetch("/api/employees", { credentials: "include" }).then(async (response) => response.ok ? response.json() as Promise<{ employees: EmployeeSummary[] }> : Promise.reject()).then((body) => setEmployees(body.employees));
  useEffect(() => { void load().catch(() => setError("Zaměstnance se nepodařilo načíst.")); }, []);
  async function save(event: FormEvent<HTMLFormElement>, employee?: EmployeeSummary) { event.preventDefault(); setError(""); const data = new FormData(event.currentTarget); const response = await fetch(employee ? `/api/employees/${employee.id}` : "/api/employees", { method: employee ? "PATCH" : "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ employeeNumber: data.get("employeeNumber"), displayName: data.get("displayName"), email: data.get("email"), ...(!employee && { password: data.get("password") }), roles: data.getAll("roles"), ...(employee && { reason: data.get("reason") }) }) }); if (!response.ok) { const body = await response.json().catch(() => ({ error: "Účet se nepodařilo uložit." })) as { error?: string }; setError(body.error ?? "Účet se nepodařilo uložit."); return; } setShowCreate(false); setEditTarget(null); await load(); if (employee?.id === user.employeeId) window.location.reload(); }
  async function changeState(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!stateTarget) return; const data = new FormData(event.currentTarget); const response = await fetch(`/api/employees/${stateTarget.id}/state`, { method: "PATCH", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify({ active: !stateTarget.isActive, reason: data.get("reason") }) }); if (!response.ok) { const body = await response.json().catch(() => ({ error: "Stav se nepodařilo změnit." })) as { error?: string }; setError(body.error ?? "Stav se nepodařilo změnit."); return; } setStateTarget(null); await load(); }
  const employeeForm = (employee?: EmployeeSummary) => <form key={employee?.id ?? "new"} className="employee-form" onSubmit={(event) => void save(event, employee)}><label>Osobní číslo<input name="employeeNumber" required maxLength={40} defaultValue={employee?.employeeNumber} /></label><label>Jméno<input name="displayName" required maxLength={160} defaultValue={employee?.displayName} /></label><label>E-mail<input name="email" type="email" required defaultValue={employee?.email} /></label>{!employee && <label>Dočasné heslo<input name="password" type="password" required minLength={12} /></label>}<fieldset><legend>Role</legend>{roleOptions.map((role) => <label className="checkbox" key={role.code}><input type="checkbox" name="roles" value={role.code} defaultChecked={employee ? employee.roles.includes(role.code) : role.code === "WORKER"} /> {role.name}</label>)}</fieldset>{employee && <label className="employee-reason">Důvod změny<input name="reason" required minLength={3} maxLength={500} /></label>}<button>{employee ? "Uložit zaměstnance" : "Vytvořit účet"}</button>{employee && <button type="button" className="ghost" onClick={() => setEditTarget(null)}>Zrušit</button>}</form>;
  return <section className="management-panel"><div className="section-heading"><div><p className="eyebrow">SPRÁVA PŘÍSTUPŮ</p><h3>Zaměstnanci a práva</h3></div><button className="inline-action" onClick={() => { setShowCreate((value) => !value); setEditTarget(null); }}>{showCreate ? "Zavřít" : "Nový zaměstnanec"}</button></div>{error && <p className="error" role="alert">{error}</p>}{showCreate && employeeForm()}{editTarget && employeeForm(editTarget)}<div className="employee-list">{employees.map((employee) => <div className={`employee-row ${employee.isActive ? "" : "inactive"}`} key={employee.id}><div><strong>{employee.displayName}</strong><span>{employee.employeeNumber} · {employee.email}</span></div><span className="role-list">{employee.roles.join(" · ")}</span><div className="row-actions"><button className="table-action" onClick={() => { setEditTarget(employee); setShowCreate(false); }}>Upravit</button><button className="table-action" disabled={employee.id === user.employeeId} onClick={() => setStateTarget(employee)}>{employee.isActive ? "Deaktivovat" : "Aktivovat"}</button></div></div>)}</div>{stateTarget && <form className="state-dialog" onSubmit={changeState}><div><strong>{stateTarget.isActive ? "Deaktivovat" : "Aktivovat"}: {stateTarget.displayName}</strong><button type="button" className="close-button" onClick={() => setStateTarget(null)}>×</button></div><label>Důvod<input name="reason" required minLength={3} maxLength={500} autoFocus /></label><button>{stateTarget.isActive ? "Potvrdit deaktivaci" : "Potvrdit aktivaci"}</button></form>}</section>;
}
