import { adminApprovalCorrectionSchema, adminBreakUpdateSchema, adminMachineUsageUpdateSchema, adminVehicleTripUpdateSchema, adminWorkEntryUpdateSchema } from "@zenops/contracts";
import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { requirePermission, type AuthorizationHook } from "./authorization.js";
import type { Database } from "./db.js";

const entryParams = z.object({ entryId: z.string().uuid() });
export function registerAdminRecordRoutes(app: FastifyInstance, db: Database, requireTrustedOrigin: AuthorizationHook): void {
  app.get("/api/admin/workdays", { preHandler: requirePermission("approval.admin.manage") }, async (request, reply) => {
    const query = z.object({ date: z.iso.date() }).safeParse(request.query);
    if (!query.success) return reply.code(400).send({ error: "Neplatné datum." });
    const workDays = await db`
      select wd.id,wd.work_date,wd.shift_type,wd.state,e.id as employee_id,e.display_name,
        coalesce((select json_agg(json_build_object('id',we.id,'projectId',p.id,'projectCode',p.code,'projectName',p.name,'workTypeCode',wt.code,'workTypeName',wt.name,'workActivityCode',wa.code,'startAt',we.start_at,'endAt',we.end_at,'description',we.description,'state',we.state,'machineUsage',(select json_build_object('id',mu.id,'machineId',mu.machine_id,'machineCode',m.code,'startMth',mu.entered_start_mth,'endMth',mu.end_mth,'fuelConsumed',mu.fuel_consumed,'fuelRefuelled',mu.fuel_refuelled,'attachmentIds',coalesce((select json_agg(au.attachment_id) from attachment_usages au where au.machine_usage_id=mu.id),'[]')) from machine_usages mu join machines m on m.id=mu.machine_id where mu.work_entry_id=we.id)) order by we.start_at) from work_entries we join projects p on p.id=we.project_id join work_types wt on wt.id=we.work_type_id left join work_activities wa on wa.id=we.work_activity_id where we.work_day_id=wd.id),'[]') as entries,
        coalesce((select json_agg(json_build_object('id',b.id,'startAt',b.start_at,'endAt',b.end_at) order by b.start_at) from break_entries b where b.work_day_id=wd.id),'[]') as breaks,
        coalesce((select json_agg(json_build_object('id',vt.id,'vehicleId',vt.vehicle_id,'vehicleCode',v.code,'startAt',vt.start_at,'endAt',vt.end_at,'startOdometerKm',vt.start_odometer_km,'endOdometerKm',vt.end_odometer_km,'fuelConsumed',vt.fuel_consumed,'fuelRefuelled',vt.fuel_refuelled,'note',vt.note,'passengerEmployeeIds',coalesce((select json_agg(vtp.employee_id) from vehicle_trip_participants vtp where vtp.vehicle_trip_id=vt.id and vtp.role='PASSENGER'),'[]')) order by vt.start_at) from vehicle_trips vt join vehicles v on v.id=vt.vehicle_id where vt.driver_work_day_id=wd.id),'[]') as vehicle_trips
      from work_days wd join employees e on e.id=wd.employee_id where wd.work_date=${query.data.date} order by e.display_name
    `;
    return { workDays };
  });

  app.patch("/api/admin/work-entries/:entryId", { preHandler: [requireTrustedOrigin, requirePermission("approval.admin.manage")] }, async (request, reply) => {
    const params = entryParams.safeParse(request.params); const parsed = adminWorkEntryUpdateSchema.safeParse(request.body);
    if (!params.success || !parsed.success) return reply.code(400).send({ error: "Neplatná oprava pracovního úseku." });
    try {
      const result = await db.begin(async (transaction) => {
        const before = await transaction<Array<{ id: string; workDayId: string; workDate: string; state: string }>>`select we.id,we.work_day_id,wd.work_date,we.state from work_entries we join work_days wd on wd.id=we.work_day_id join monthly_periods mp on mp.id=wd.monthly_period_id where we.id=${params.data.entryId} and mp.state='OPEN' for update of we`;
        if (!before[0]) return null;
        const context = await transaction<Array<{ projectId: string; workTypeId: string; workActivityId: string|null }>>`select p.id as project_id,wt.id as work_type_id,wa.id as work_activity_id from projects p join work_types wt on wt.code=${parsed.data.workTypeCode} and wt.is_active left join work_activities wa on wa.work_type_id=wt.id and wa.code=${parsed.data.workActivityCode ?? null} and wa.is_active where p.id=${parsed.data.projectId} and (not wt.requires_activity or wa.id is not null)`;
        if (!context[0]) return null;
        const [projectDay] = await transaction<Array<{id:string}>>`insert into project_days(project_id,work_date) values(${context[0].projectId},${before[0].workDate}) on conflict(project_id,work_date) do update set project_id=excluded.project_id returning id`;
        const [after] = await transaction`update work_entries set project_id=${context[0].projectId},project_day_id=${projectDay!.id},work_type_id=${context[0].workTypeId},work_activity_id=${context[0].workActivityId},start_at=${parsed.data.startAt},end_at=${parsed.data.endAt},description=${parsed.data.description ?? null},updated_at=now() where id=${params.data.entryId} returning *`;
        await transaction`insert into audit_logs(actor_user_id,action,entity_type,entity_id,before_data,after_data,reason) values(${request.sessionUser!.id},'WORK_ENTRY_ADMIN_CORRECTED','WORK_ENTRY',${params.data.entryId},${transaction.json(before[0])},${transaction.json(after!)},${parsed.data.reason})`;
        return after;
      });
      if (!result) return reply.code(409).send({ error: "Úsek nebyl nalezen, měsíc je uzavřen nebo údaje nejsou platné." });
      return { entry: result };
    } catch(error) { if(typeof error === "object" && error && "code" in error && error.code === "23P01") return reply.code(409).send({error:"Opravený čas se překrývá s jiným záznamem."}); throw error; }
  });

  app.post("/api/admin/work-entries/:entryId/decision", { preHandler: [requireTrustedOrigin, requirePermission("approval.admin.manage")] }, async (request, reply) => {
    const params=entryParams.safeParse(request.params); const parsed=adminApprovalCorrectionSchema.safeParse(request.body); if(!params.success||!parsed.success) return reply.code(400).send({error:"Neplatná oprava schválení."});
    const result=await db.begin(async(transaction)=>{ const rows=await transaction<Array<{id:string;workDayId:string;state:string}>>`select we.id,we.work_day_id,we.state from work_entries we join work_days wd on wd.id=we.work_day_id join monthly_periods mp on mp.id=wd.monthly_period_id where we.id=${params.data.entryId} and mp.state='OPEN' for update of we`; if(!rows[0]) return null; const before=rows[0]; await transaction`insert into approvals(work_entry_id,action,approver_employee_id,reason) values(${before.id},${parsed.data.action},${request.sessionUser!.employeeId},${parsed.data.action==='RETURNED'?parsed.data.reason:null})`; await transaction`update work_entries set state=${parsed.data.action},updated_at=now() where id=${before.id}`; const states=await transaction<Array<{state:string}>>`select state from work_entries where work_day_id=${before.workDayId}`; const aggregate=states.some(x=>x.state==='RETURNED')?'RETURNED':states.every(x=>x.state==='APPROVED')?'APPROVED':states.some(x=>x.state==='APPROVED')?'PARTIALLY_APPROVED':'SUBMITTED'; await transaction`update work_days set state=${aggregate},updated_at=now() where id=${before.workDayId}`; await transaction`insert into audit_logs(actor_user_id,action,entity_type,entity_id,before_data,after_data,reason) values(${request.sessionUser!.id},'APPROVAL_ADMIN_CORRECTED','WORK_ENTRY',${before.id},${transaction.json(before)},${transaction.json({state:parsed.data.action,workDayState:aggregate})},${parsed.data.reason})`; return {entryId:before.id,state:parsed.data.action,workDayState:aggregate}; }); if(!result) return reply.code(409).send({error:"Záznam nebyl nalezen nebo měsíc je uzavřen."}); return {decision:result};
  });

  app.patch("/api/admin/breaks/:id", { preHandler:[requireTrustedOrigin,requirePermission("approval.admin.manage")] }, async(request,reply)=>{const id=z.string().uuid().safeParse((request.params as {id?:string}).id);const parsed=adminBreakUpdateSchema.safeParse(request.body);if(!id.success||!parsed.success)return reply.code(400).send({error:"Neplatná oprava přestávky."});try{const result=await db.begin(async t=>{const before=await t`select b.* from break_entries b join work_days wd on wd.id=b.work_day_id join monthly_periods mp on mp.id=wd.monthly_period_id where b.id=${id.data} and mp.state='OPEN' for update of b`;if(!before[0])return null;const[after]=await t`update break_entries set start_at=${parsed.data.startAt},end_at=${parsed.data.endAt} where id=${id.data} returning *`;await t`insert into audit_logs(actor_user_id,action,entity_type,entity_id,before_data,after_data,reason) values(${request.sessionUser!.id},'BREAK_ADMIN_CORRECTED','BREAK_ENTRY',${id.data},${t.json(before[0]!)},${t.json(after!)},${parsed.data.reason})`;return after});if(!result)return reply.code(409).send({error:"Přestávka nebyla nalezena nebo měsíc je uzavřen."});return{break:result}}catch(error){if(typeof error==='object'&&error&&'code'in error&&error.code==='23P01')return reply.code(409).send({error:"Přestávka se překrývá s jiným záznamem."});throw error}});

  app.patch("/api/admin/machine-usages/:id", { preHandler:[requireTrustedOrigin,requirePermission("approval.admin.manage")] }, async(request,reply)=>{const id=z.string().uuid().safeParse((request.params as {id?:string}).id);const parsed=adminMachineUsageUpdateSchema.safeParse(request.body);if(!id.success||!parsed.success)return reply.code(400).send({error:"Neplatná oprava použití stroje."});try{const result=await db.begin(async t=>{const before=await t`select mu.*,we.start_at as entry_start,we.end_at as entry_end from machine_usages mu join work_entries we on we.id=mu.work_entry_id join work_days wd on wd.id=we.work_day_id join monthly_periods mp on mp.id=wd.monthly_period_id where mu.id=${id.data} and mp.state='OPEN' for update of mu`;if(!before[0])return null;const[after]=await t`update machine_usages set machine_id=${parsed.data.machineId},entered_start_mth=${parsed.data.startMth??null},end_mth=${parsed.data.endMth??null},fuel_consumed=${parsed.data.fuelConsumed??null},fuel_refuelled=${parsed.data.fuelRefuelled??null} where id=${id.data} returning *`;await t`delete from attachment_usages where machine_usage_id=${id.data}`;for(const attachmentId of parsed.data.attachmentIds)await t`insert into attachment_usages(machine_usage_id,work_entry_id,attachment_id,start_at,end_at) values(${id.data},${after!.workEntryId},${attachmentId},${before[0]!.entryStart},${before[0]!.entryEnd})`;await t`insert into audit_logs(actor_user_id,action,entity_type,entity_id,before_data,after_data,reason) values(${request.sessionUser!.id},'MACHINE_USAGE_ADMIN_CORRECTED','MACHINE_USAGE',${id.data},${t.json(before[0]!)},${t.json(after!)},${parsed.data.reason})`;return after});if(!result)return reply.code(409).send({error:"Použití stroje nebylo nalezeno nebo měsíc je uzavřen."});return{usage:result}}catch(error){if(typeof error==='object'&&error&&'code'in error&&(error.code==='23P01'||error.code==='23505'))return reply.code(409).send({error:"Stroj nebo příslušenství koliduje s jiným použitím."});throw error}});

  app.patch("/api/admin/vehicle-trips/:id", { preHandler:[requireTrustedOrigin,requirePermission("approval.admin.manage")] }, async(request,reply)=>{const id=z.string().uuid().safeParse((request.params as {id?:string}).id);const parsed=adminVehicleTripUpdateSchema.safeParse(request.body);if(!id.success||!parsed.success)return reply.code(400).send({error:"Neplatná oprava jízdy."});try{const result=await db.begin(async t=>{const before=await t`select vt.* from vehicle_trips vt join work_days wd on wd.id=vt.driver_work_day_id join monthly_periods mp on mp.id=wd.monthly_period_id where vt.id=${id.data} and mp.state='OPEN' for update of vt`;if(!before[0])return null;if(parsed.data.passengerEmployeeIds.includes(before[0]!.driverEmployeeId))throw Object.assign(new Error("Řidič nemůže být cestující."),{statusCode:422});const[after]=await t`update vehicle_trips set vehicle_id=${parsed.data.vehicleId},start_at=${parsed.data.startAt},end_at=${parsed.data.endAt},start_odometer_km=${parsed.data.startOdometerKm},end_odometer_km=${parsed.data.endOdometerKm},fuel_consumed=${parsed.data.fuelConsumed??null},fuel_refuelled=${parsed.data.fuelRefuelled??null},note=${parsed.data.note??null},updated_at=now() where id=${id.data} returning *`;await t`delete from vehicle_trip_participants where vehicle_trip_id=${id.data} and role='PASSENGER'`;for(const employeeId of parsed.data.passengerEmployeeIds)await t`insert into vehicle_trip_participants(vehicle_trip_id,employee_id,role) values(${id.data},${employeeId},'PASSENGER')`;await t`insert into audit_logs(actor_user_id,action,entity_type,entity_id,before_data,after_data,reason) values(${request.sessionUser!.id},'VEHICLE_TRIP_ADMIN_CORRECTED','VEHICLE_TRIP',${id.data},${t.json(before[0]!)},${t.json(after!)},${parsed.data.reason})`;return after});if(!result)return reply.code(409).send({error:"Jízda nebyla nalezena nebo měsíc je uzavřen."});return{trip:result}}catch(error){if(typeof error==='object'&&error&&'code'in error&&error.code==='23P01')return reply.code(409).send({error:"Vozidlo v tomto čase používá jiná jízda."});throw error}});
}
